"""empty message

Revision ID: 294484e79dc0
Revises: 826c9f7509f0
Create Date: 2016-04-16 20:59:26.239000

"""

# revision identifiers, used by Alembic.
revision = '294484e79dc0'
down_revision = '826c9f7509f0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'entry', 'user', ['author_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'entry', type_='foreignkey')
    op.drop_column('entry', 'author_id')
    ### end Alembic commands ###
