"""empty message

Revision ID: a9afa760ed0e
Revises: 826c9f7509f0
Create Date: 2016-04-17 18:29:35.985000

"""

# revision identifiers, used by Alembic.
revision = 'a9afa760ed0e'
down_revision = '826c9f7509f0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'entry', 'user', ['author_id'], ['id'])
    op.add_column('user', sa.Column('admin', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'admin')
    op.drop_constraint(None, 'entry', type_='foreignkey')
    ### end Alembic commands ###
